---
draft: false
date: "2023-06-11"
diagram: true
authors: 
- Keven Bluteau
image:
  caption: ""
  placement: 3
math: true
title: 2023 Update on the Media Climate Change Concerns Index
active: true  # Activate this widget? true/false
---

Update of the Media Climate Change Concerns (MCCC) index! The index ranges now from January 2003 to August 2022. The MCCC is constructed from major U.S. newspapers and newswires to proxy for climate change concerns. Check our work published at Management Science for details. 

We have extended the MCCC index and its subindices (topical and thematic) beyond their original timeframe of 2003 to June 2018, now encompassing data up to August 2022. This update provides approximately four years of additional data, allowing for a more comprehensive understanding of media coverage of climate change.

To ensure consistency and accuracy, we have diligently followed the same procedure used to generate the original dataset while accounting for necessary changes in methodology for the new data (from July 2018 to August 2022).

We want to highlight a few key points regarding the update process:

*Exclusion of The Houston Chronicle: Unfortunately, the research team no longer has access to The Houston Chronicle and therefore, it is not included in the updated index.

*Use of Alternative News Aggregators: For the remaining newspapers, we relied on alternative news aggregators to obtain the data for some of them, ensuring that the coverage is as comprehensive as possible.

*Upgrade to LIWC2022 Software: Due to the unavailability of the LIWC2015 software, we utilized the LIWC2022 software to compute the concerns score of the new documents. It is important to note that although we used the 2015 dictionary within the 2022 software, we observed slight differences in the concerns scores generated by both software.

To assess the impact of these changes, we conducted a thorough analysis using one year of overlapping data. By generating new indices and computing correlations with the original indices, we found that the correlation was consistently above 0.95 for all indices. This suggests that the methodological changes implemented during the update did not fundamentally invalidate the updated data. 

For the topical and thematic indices, we used the same model trained with 2003-2018 data to compute the topicality of the updated indices. This approach ensures continuity in the topical model, allowing for meaningful comparisons between the new and previous data.

We hope this update will enhance the utility of the Media Climate Change Concerns Index, empowering academic researchers and industry practitioners to gain deeper insights into the evolving landscape of media coverage of climate change. 

Please refer to this article when using the index in your research:

[Ardia, D., Bluteau, K., Boudt, K., Inghelbrecht, K. (2023). Climate change concerns and the performance of green versus brown stocks. Management Science](https://doi.org/10.1287/mnsc.2022.4636).

Download the data [here](https://sentometrics-research.com/download/mccc/)

