---
# A Demo section created with the Blank widget.
# Any elements can be added in the body: https://sourcethemes.com/academic/docs/writing-markdown-latex/
# Add more sections by duplicating this file and customizing to your requirements.

widget: "blank"  # See https://sourcethemes.com/academic/docs/page-builder/
headless: true  # This file represents a page section.
active: true  # Activate this widget? true/false
weight: 3 # Order that this section will appear.

title: "Indices"
subtitle: ""

design:
  columns: "1"


---

```{r, echo=FALSE, message=FALSE,  warning=FALSE}
library(httr)
library(rdrop2)
library(data.table)
library(plotly)    
library(RcppRoll)
library(lubridate)
library(openssl)
library(timeDate)
Holidays = function(country, start, end){
    year = unique(lubridate::year(  seq(start, end, by = 1)))
    easter = timeDate::Easter(year)
    if(country == "BE"){
    easter = as.Date(easter)
    holiday = easter #easter
    holiday = c(holiday, easter+1) #Easter Monday
    holiday = c(holiday, easter+39) #Ascension
    holiday = c(holiday, easter+49) #Pentecost
    holiday = c(holiday, easter+50) #Pentecost Monday
    holiday = c(holiday,
                 as.Date(paste0(year,"-05-01")), # Labour Day
                 as.Date(paste0(year,"-07-21")), # Belgian National Day
                 as.Date(paste0(year,"-08-15")), # Assumption of Mary
                 as.Date(paste0(year,"-11-01")), # All Saints' Day
                 as.Date(paste0(year,"-11-11")), # Remembrance Day
                 as.Date(paste0(year,"-12-25")), # Christmas
                 as.Date(paste0(year,"-01-01")), # New year
                 as.Date(paste0("2000","-02-29")), #missing leap years 29
                 as.Date(paste0("2004","-02-29")), #missing leap years 29
                 as.Date(paste0("2008","-02-29")), #missing leap years 29
                 as.Date(paste0("2012","-02-29")), #missing leap years 29
                 as.Date(paste0("2016","-02-29")), #missing leap years 29
                 as.Date(paste0("2020","-02-29")), #missing leap years 29
                 as.Date(paste0("2009","-10-19")), #missing data
                 as.Date(paste0("2009","-10-20")), #missing data
                 as.Date(paste0("2009","-10-21")), #missing data
                 as.Date(paste0("2009","-10-22")), #missing data
                 as.Date(paste0("2009","-10-23")), #missing data
                 as.Date(paste0("2011","-10-28")), #missing data
                 as.Date(paste0("2011","-10-29")), #missing data
                 as.Date(paste0("2011","-10-29")), #missing data
                 as.Date(paste0("2011","-10-31")), #missing data
                 as.Date(paste0("2013","-10-04")), #missing data
                 as.Date(paste0("2013","-10-08")), #missing data
                 as.Date(paste0("2013","-10-15")), #missing data
                 as.Date(paste0("2013","-10-16")), #missing data
                 as.Date(paste0("2013","-10-18")), #missing data
                 as.Date(paste0("2013","-10-29")) #missing data
                )
    }
    return(as.Date(holiday))
    
}
transform_data = function(x, country){
  start = as.Date("2000-01-01")
  end = as.Date(Sys.time())
  dates_total = seq(start, end, by = 1)
  dat  = data.frame(timestamp = dates_total)
  
  x$timestamp =as.Date(x$timestamp)
  id.match = match(dat$timestamp,x$timestamp)
  dat$name = x$name[1]
  dat$value[!is.na(id.match)] = x$value
  dat$value[is.na(dat$value)] = 0
  dat$value[lubridate::wday(dat$timestamp) == 1] = NA
  if(dat$name[1] == "epu-wallonia"){
    dat$value[lubridate::year(dat$timestamp) == 2006] = NA
  }
  holiday = Holidays(country = country, start = start,end = end)
  dat$value[!is.na(match(dat$timestamp, holiday))] = NA
  dat$MA = NA
  dat$ind = NA
  dat$MA[-1:-29] = RcppRoll::roll_mean(dat$value, 30,na.rm = TRUE)
  dat$ind[-1:-29] = RcppRoll::roll_sum(!is.na(dat$value), 30,na.rm = TRUE)
  dat = dat[-1:-29,]
  
  dat$MA[lubridate::wday(dat$timestamp) == 1] = NA
  dat$MA[dat$ind < 20] = NA
  dat$value[lubridate::wday(dat$timestamp) == 1] = NA
  dat$MA[!is.na(match(dat$timestamp, holiday))] = NA
  dat = dat[-1,]
  return(dat)
  
}
```
```{r, echo=FALSE, message=FALSE,  warning=FALSE}
auth <- POST("https://api-dev.sentometrics.com/token", 
             body = list(username=Sys.getenv("sento_username"),
                         password=Sys.getenv("sento_password")))
key <- sha256(charToRaw(Sys.getenv("DP_pass")))
auth_drop = readRDS("../../vault/credential.rds")
auth_drop <- unserialize(aes_cbc_decrypt(auth_drop, key = key))
EPU_flanders_tmp <- data.table::rbindlist(content(GET("https://api-dev.sentometrics.com/index/values/epu-flanders", 
                                                        query = list(version="1.4.0",
                                                                frequency="D",
                                                                start= "2000-01-01",
                                                                end= as.character(as.Date(Sys.time()))),
                                                        add_headers(Authorization = paste0("Bearer ", content(auth)$access_token)))))

EPU_flanders = transform_data(EPU_flanders_tmp, country = "BE")

EPU_belgium_tmp <- data.table::rbindlist(content(GET("https://api-dev.sentometrics.com/index/values/epu-belgium", 
                                                     query = list(version="1.4.0",
                                                                frequency="D",
                                                                start= "2000-01-01",
                                                                end= as.character(as.Date(Sys.time()))),
                                                     add_headers(Authorization = paste0("Bearer ", content(auth)$access_token)))))

EPU_belgium = transform_data(EPU_belgium_tmp, country = "BE")

EPU_wal_tmp <- data.table::rbindlist(content(GET("https://api-dev.sentometrics.com/index/values/epu-wallonia", 
                                                    query = list(version="1.4.0",
                                                                frequency="D",
                                                                start= "2000-01-01",
                                                                end= as.character(as.Date(Sys.time()))),
                                                    add_headers(Authorization = paste0("Bearer ", content(auth)$access_token)))))

EPU_wal = transform_data(EPU_wal_tmp, country = "BE")

Indices = data.frame(EPU_belgium[,c(1:2)],
                     epu_belgium_MA = EPU_belgium[,"MA"],
                        epu_belgium_DV = EPU_belgium[,"value"],
                     epu_flanders_MA = EPU_flanders[,"MA"],
                       epu_flanders_DV = EPU_flanders[,"value"],
                     epu_wallonia_MA = EPU_wal[,"MA"],
                      epu_wallonia_DV = EPU_wal[,"value"])

if(any(is.na(tail(Indices[,c(-1,-2)],1)))){
   Indices =  Indices[-nrow(Indices),]
}

if(any(tail(Indices[,c(-1,-2)],1) == 0)){
 Indices =  Indices[-nrow(Indices),]
}

Indices[c(-1,-2)] = round(Indices[c(-1,-2)], 2)
Indices = Indices[,-2]
colnames(Indices)[1] = "date"
export = Indices
export[,8] = ""
export[1,8] = "When using one of the indices, please cite as follows:"
export[2,8] = "Algaba, A., Borms, S., Boudt, K. & Van Pelt, J. (2020). The Economic Policy Uncertainty index for Flanders, Wallonia and Belgium. Research note. doi: 10.2139/ssrn.3580000"
export[3,8] = "The paper is available also at: https://www.financialforum.be/doc/doc/review/2020/bfw-digitaal-editie6-2020-06-algaba-borms-boudt-vanpelt.pdf"
export[4,8] = "These data can be used freely with attribution to the authors, the paper, and the website."
export[5,8] = "Monthly EPU available at: https://www.policyuncertainty.com/belgium_monthly.html"
export[6,8] = "NA means that for this day the media data was not available for reasons of holidays (or Sundays) or technical issues in the database."
export[7,8] = "These indices are not intended for trading purposes. These indices are not appropriate for the purposes of making a decision to carry out a transaction or trade. Nor does it provide any form of advice (investment, tax, legal) amounting to investment advice, or make any recommendations regarding particular financial instruments, investments or products. These indices may discontinue or change at any time, without notice. We do not guarantee or warrant the accuracy, completeness or timeliness of the indices. These indices are provided “as is”, without any warranties. Neither the providers (sentometrics-research.com) of these indices nor any of its affiliates shall be liable for any loss resulting from use of these indices."
colnames(export)[8] = "Note"
write.csv(export, 'Indices.csv')
drop_upload('Indices.csv',path = "files", dtoken = auth_drop)
```

```{r, echo=FALSE, message=FALSE,  warning=FALSE, out.width = "98%", out.height="95%"}
p <- plot_ly(Indices,   
              type = 'scatter', 
              mode = 'lines',
              x = ~date, name = "epu-belgium",
             hoverinfo = 'text',
              y = ~epu_belgium_MA,line = list(color = "#00AEFF"),
              text = ~paste('Date: ', date, '\n',
                           'Index: ', "epu-belgium", '\n',
                           '30-day moving average: ', epu_belgium_MA, '\n',
                           'Daily Value: ', epu_belgium_DV, '\n')
   )
             
  
p <- add_trace(p,
              type = 'scatter', 
              mode = 'lines',
              x = ~date,line = list(color = "#00AEFF"), 
              y = ~epu_flanders_MA,name = "epu-flanders",
              hoverinfo = 'text',
              text = ~paste('Date: ', date, '\n',
                           'Index: ', "epu-flanders", '\n',
                           '30-day moving average: ', epu_flanders_MA, '\n',
                           'Daily Value: ', epu_flanders_DV, '\n'), visible = FALSE
)

p <- add_trace(p,
              type = 'scatter', 
              mode = 'lines',
              x = ~date,line = list(color = "#00AEFF"),
              y = ~epu_wallonia_MA,name = "epu-wallonia",
              hoverinfo = 'text',
              text = ~paste('Date: ', date, '\n',
                           'Index: ', "epu-wallonia", '\n',
                           '30-day moving average: ', epu_wallonia_MA, '\n',
                           'Daily Value: ', epu_wallonia_DV, '\n'), visible = FALSE
)


p = hide_legend(p)


p =  layout(p,
        autosize=T,
        height = 700,
         xaxis  = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 3,
            label = "3 mo",
            step = "month",
            stepmode = "backward"),
          list(
            count = 6,
            label = "6 mo",
            step = "month",
            stepmode = "backward"),
          list(
            count = 1,
            label = "1 yr",
            step = "year",
            stepmode = "backward"),
          list(
            count = 1,
            label = "YTD",
            step = "year",
            stepmode = "todate"),
          list(step = "all"))),
      rangeslider = list(type = "date"),
      title="date"),
         yaxis=list(title="EPU Belgium", range = c(0,500)),
    updatemenus = list(
      list(
        type = "dropdown",
        label = 'Category',
        buttons = list(
          list(method = "update",
               args = list(
                 list(visible = c(TRUE, FALSE, FALSE)),
                 list(yaxis =  list(title="EPU Belgium", range = c(0,500)))     
                ),
               label = "epu-belgium"),
          list(method = "update",
               args = list(
                 list(visible =  c(FALSE, TRUE, FALSE)),
                 list(yaxis =  list(title="EPU Flanders", range = c(0,500)))     
                ),
               label = "epu-flanders"),
          list(method = "update",
               args = list(
                 list(visible =  c(FALSE, FALSE, TRUE)),
                 list(yaxis =  list(title="EPU Wallonia", range = c(0,500)))
                ),
               label = "epu-wallonia")
        )
      )
    )
  ) 
p = plotly::toWebGL(p)

p
```

[Download file](https://www.dropbox.com/s/aftvxm26sa020hf/Indices.csv?dl=1)
