# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home-1"
  weight = 1

[[main]]
  name = "Indices"
  url = "#indices"
  weight = 3
  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 4

[[main]]
  name = "Software"
  url = "#software"
  weight = 5

[[main]]
  name = "Research"
  url = "#research"
  weight = 6

[[main]]
  name = "Sponsors"
  url = "#sponsors"
  weight = 7
  
[[main]]
  name = "Contribute"
  url = "#contribute"
  weight = 8