language: r
dist: xenial
latex: false

cache:
  packages: yes
  directories:
    - $HOME/bin

branches:
  only:
    - master

script:
  - Rscript build_website.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: SentometricsResearch/sentometricsresearch.github.io 
  target_branch: master