language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:	
  packages: yes	
  directories:	
    - $HOME/bin	

before_install:
    openssl aes-256-cbc -K $encrypted_439d8880b5c8_key -iv $encrypted_439d8880b5c8_iv -in vault/credential.rds.enc -out vault/credential.rds -d
script:
  - Rscript build_website.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: SentometricsResearch/sentometricsresearch.github.io 
  target_branch: master
  committer_from_gh: true
  fqdn: sentometrics-research.com
