install.packages("renv")
renv::restore()
renv::activate()
install.packages("blogdown")
blogdown::install_hugo(version = "0.75.0")
blogdown::build_site(build_rmd = TRUE)
blogdown::hugo_build()
file.copy("CNAME", "public")
file.copy(".nojekyll", "public")
print(Sys.Date())

