---
draft: false
date: "2025-07-25"
diagram: true
authors: 
- Keven Bluteau
image:
  caption: ""
  placement: 3
math: true
title: 2025 Update on the Media Climate Change Concerns Index
active: true  # Activate this widget? true/false
---

Update of the Media Climate Change Concerns (MCCC) index! The index ranges now from January 2003 to June 2025. The MCCC is constructed from major U.S. newspapers and newswires to proxy for climate change concerns. Check our work published at Management Science for details. 

We have extended the MCCC index and its subindices (topical and thematic) beyond their updated timeframe of 2003 to June 2024, now encompassing data up to June 2025. This update provides one year of additional data, allowing for a more comprehensive understanding of media coverage of climate change.

No methodological change was required for this update (for the changes compared to the original index, see the 2023 update)

We hope this update will enhance the utility of the Media Climate Change Concerns Index, empowering academic researchers and industry practitioners to gain deeper insights into the evolving landscape of media coverage of climate change. 

Please refer to this article when using the index in your research:

[Ardia, D., Bluteau, K., Boudt, K., Inghelbrecht, K. (2023). Climate change concerns and the performance of green versus brown stocks. Management Science](https://doi.org/10.1287/mnsc.2022.4636).

Download the data [here](https://sentometrics-research.com/download/mccc/)

