on:
  push:
     branches:
       - master

name: deploy website

jobs:
  blogdown:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Build site
        run:  Rscript ./build_website.R
        env:
          sento_username: ${{ secrets.SENTO_USERNAME }}
          sento_password: ${{ secrets.SENTO_PASSWORD }}
          DP_pass: ${{ secrets.DP_PASS }}
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: 'SentometricsResearch'
          destination-repository-name: 'sentometricsresearch.github.io'
          user-email: keven.bluteau@hec.ca
          target-branch: test
